### ISSUE TITLE
warn ESLintError on subscribe.js (Mailchimp)

### ISSUE THREAD

**Issue by charles-hood** [TheRobBrennan/woatw#40]
warn ESLintError:
\mailchimp\subscribe.js
74:15  warning  A control must be associated with a text label  jsx-a11y/control-has-associated-label

**Comment by charles-hood** [comment]
I think it's as simple as adding aria-label

              <input aria-label="email"
                style={{ backgroundColor: 'white' }}
                onChange={this._handleEmailChange}
                required
              />
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <button type="button" aria-label="Save" class="icon-save" 
               onClick={this._handleFormSubmit}>Subscribe</button>

**Comment by TheRobBrennan** [comment]
Ah yeah - I use Prettier, myself.

I did play around a bit with ESLint just to see, and sure enough ESLint is unhappy about a lot of things - `✖ 1311 problems (1311 errors, 0 warnings)`

For now, I'll just sweep that under the rug. Great find, though. =)
